version: '3.3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/project
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: php-fpm-mysql
    volumes:
      - .:/var/www/project
    links:
      - db
  db:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0"
    volumes:
      - ./docker/mysql/datadir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app

